/*******************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only
* intended for use with Renesas products. No other uses are authorized. This
* software is owned by Renesas Electronics Corporation and is protected under
* all applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
* THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT
* LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
* AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.
* TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS
* ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE
* FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR
* ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE
* BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software
* and to discontinue the availability of this software. By using this software,
* you agree to the additional terms and conditions found by accessing the
* following link:
* http://www.renesas.com/disclaimer
* Copyright (C) 2017 Renesas Electronics Corporation. All rights reserved.
*******************************************************************************/

/*******************************************************************************
 * File Name : r_g3_cmd.c
 * Description : G3 Command define
 ******************************************************************************/

#ifndef R_G3_CMD_H
#define R_G3_CMD_H

/******************************************************************************
Macro definitions
******************************************************************************/

/* PRQA S 0857 EOF */
#define R_G3_MAKE_FUNCID(type, id, cmd)  ((uint16_t)((type) << 12u) | (uint16_t)((id) << 8u) | (cmd))
#define R_G3_GET_CMDTYPE(funcId)         ((uint8_t)(((funcId) >> 12u) & 0x07))

#define R_G3_GET_UNITID(funcId)          ((uint8_t)(((funcId) >> 8u) & 0x0F))
#define R_G3_GET_CMD_ID(funcId)          ((uint8_t)((funcId) & 0xFF))

#define R_G3_CMDTYPE_REQ                        (0x00u)
#define R_G3_CMDTYPE_CNF                        (0x01u)
#define R_G3_CMDTYPE_IND                        (0x02u)
#define R_G3_CMDTYPE_RESERVE                    (0x03u)
#define R_G3_CMDTYPE_MAX                        (R_G3_CMDTYPE_RESERVE + 1u)

#define R_G3_UNITID_G3CTRL                      (0x00u)
#define R_G3_UNITID_RESERVE                     (0x01u)
#define R_G3_UNITID_G3LMACIF                    (0x02u)
#define R_G3_UNITID_G3MAC                       (0x03u)
#define R_G3_UNITID_G3ADP                       (0x04u)
#define R_G3_UNITID_G3EAP                       (0x05u)
#define R_G3_UNITID_G3HYAL                      (0x06u)
#define R_G3_UNITID_RFLMAC                      (0x0Au)  /* 0x08 | R_G3_UNITID_G3LMACIF(0x02) */
#define R_G3_UNITID_G3RFMAC                     (0x0Bu)  /* 0x08 | R_G3_UNITID_G3MAC(0x03) */
#define R_G3_UNITID_MAX                         (R_G3_UNITID_G3RFMAC + 1u)

#define R_G3_CMDID_G3_INIT                      (0x00u)
#define R_G3_CMDID_G3_DEINIT                    (0x01u)
#define R_G3_CMDID_G3_GETCONFIG                 (0x02u)
#define R_G3_CMDID_G3_SETCONFIG                 (0x03u)
#define R_G3_CMDID_G3_CLEARINFO                 (0x14u)
#define R_G3_CMDID_G3_GETINFO                   (0x15u)
#define R_G3_CMDID_G3_DUMP                      (0x18u)
#define R_G3_CMDID_G3_DUMP_ABORT                (0x19u)
#define R_G3_CMDID_G3_EVENT                     (0x20u)


#define R_G3_CMDID_MCPS_DATA                    (0x00u)
#define R_G3_CMDID_MLME_RESET                   (0x01u)
#define R_G3_CMDID_MLME_GET                     (0x02u)
#define R_G3_CMDID_MLME_SET                     (0x03u)
#define R_G3_CMDID_MLME_SCAN                    (0x04u)
#define R_G3_CMDID_MLME_START                   (0x05u)
#define R_G3_CMDID_MLME_BEACON_NOTIFY           (0x06u)
#define R_G3_CMDID_MLME_COMM_STATUS             (0x07u)
#define R_G3_CMDID_MLME_FRAMECOUNT              (0x08u)
#define R_G3_CMDID_MLME_TMR_RECEIVE             (0x09u)
#define R_G3_CMDID_MLME_TMR_TRANSMIT            (0x0Au)
#define R_G3_CMDID_G3MAC_MAX                    (R_G3_CMDID_MLME_TMR_TRANSMIT + 1u)

#define R_G3_CMDID_ADPD_DATA                    (0x00u)
#define R_G3_CMDID_ADPM_RESET                   (0x01u)
#define R_G3_CMDID_ADPM_DISCOVERY               (0x02u)
#define R_G3_CMDID_ADPM_NETWORK_START           (0x03u)
#define R_G3_CMDID_ADPM_NETWORK_JOIN            (0x04u)
#define R_G3_CMDID_ADPM_NETWORK_LEAVE           (0x05u)
#define R_G3_CMDID_ADPM_GET                     (0x06u)
#define R_G3_CMDID_ADPM_SET                     (0x07u)
#define R_G3_CMDID_ADPM_ROUTE_DISCOVERY         (0x08u)
#define R_G3_CMDID_ADPM_PATH_DISCOVERY          (0x09u)
#define R_G3_CMDID_ADPM_LBP                     (0x0Au)
#define R_G3_CMDID_ADPM_NETWORK_STATUS          (0x0Bu)
#define R_G3_CMDID_ADPM_BUFFER                  (0x0Cu)
#define R_G3_CMDID_ADPM_KEY_STATE               (0x0Du)
#define R_G3_CMDID_ADPM_ROUTE_ERROR             (0x0Eu)
#define R_G3_CMDID_ADPM_EAP_KEY                 (0x0Fu)
#define R_G3_CMDID_ADPM_FRAME_COUNTER           (0x10u)
#define R_G3_CMDID_ADPM_ROUTE_UPDATE            (0x11u)
#define R_G3_CMDID_ADPM_LOAD_SEQ_NUM            (0x12u)
#define R_G3_CMDID_ADPM_RREP                    (0x13u)
#define R_G3_CMDID_ADPM_BEACON_NOTIFY           (0x14u)

#define R_G3_CMDID_EAPM_RESET                   (0x00u)
#define R_G3_CMDID_EAPM_START                   (0x01u)
#define R_G3_CMDID_EAPM_GET                     (0x02u)
#define R_G3_CMDID_EAPM_SET                     (0x03u)
#define R_G3_CMDID_EAPM_NETWORK                 (0x04u)
#define R_G3_CMDID_EAPM_SETCLIENTINFO           (0x05u)
#define R_G3_CMDID_EAPM_NETWORK_JOIN            (0x06u)
#define R_G3_CMDID_EAPM_NETWORK_LEAVE           (0x07u)
#define R_G3_CMDID_EAPM_NEWDEVICE               (0x08u)
#define R_G3_CMDID_EAPM_EAP_KEY                 (0x09u)
#define R_G3_CMDID_EAP_MAX                      (R_G3_CMDID_EAPM_EAP_KEY + 1u)

#define R_G3_FUNCID_G3_INIT_REQ                 (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_INIT))
#define R_G3_FUNCID_G3_DEINIT_REQ               (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_DEINIT))
#define R_G3_FUNCID_G3_GETCONFIG_REQ            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_GETCONFIG))
#define R_G3_FUNCID_G3_SETCONFIG_REQ            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_SETCONFIG))
#define R_G3_FUNCID_G3_GETINFO_REQ              (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_GETINFO))
#define R_G3_FUNCID_G3_CLEARINFO_REQ            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_CLEARINFO))
#define R_G3_FUNCID_G3_DUMP_REQ                 (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_DUMP))
#define R_G3_FUNCID_G3_DUMP_ABORT_REQ           (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_DUMP_ABORT))
#define R_G3_FUNCID_G3_INIT_CNF                 (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_INIT))
#define R_G3_FUNCID_G3_DEINIT_CNF               (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_DEINIT))
#define R_G3_FUNCID_G3_GETCONFIG_CNF            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_GETCONFIG))
#define R_G3_FUNCID_G3_SETCONFIG_CNF            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_SETCONFIG))
#define R_G3_FUNCID_G3_GETINFO_CNF              (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_GETINFO))
#define R_G3_FUNCID_G3_CLEARINFO_CNF            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_CLEARINFO))
#define R_G3_FUNCID_G3_DUMP_CNF                 (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_DUMP))
#define R_G3_FUNCID_G3_DUMP_IND                 (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_DUMP))
#define R_G3_FUNCID_G3_DUMP_ABORT_CNF           (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_DUMP_ABORT))
#define R_G3_FUNCID_G3_EVENT_IND                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3CTRL, R_G3_CMDID_G3_EVENT))


#define R_G3_FUNCID_MCPS_DATA_REQ               (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3MAC, R_G3_CMDID_MCPS_DATA))
#define R_G3_FUNCID_MLME_RESET_REQ              (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_RESET))
#define R_G3_FUNCID_MLME_GET_REQ                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_GET))
#define R_G3_FUNCID_MLME_SET_REQ                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_SET))
#define R_G3_FUNCID_MLME_SCAN_REQ               (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_SCAN))
#define R_G3_FUNCID_MLME_START_REQ              (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_START))
#define R_G3_FUNCID_MCPS_DATA_CNF               (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3MAC, R_G3_CMDID_MCPS_DATA))
#define R_G3_FUNCID_MLME_RESET_CNF              (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_RESET))
#define R_G3_FUNCID_MLME_GET_CNF                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_GET))
#define R_G3_FUNCID_MLME_SET_CNF                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_SET))
#define R_G3_FUNCID_MLME_SCAN_CNF               (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_SCAN))
#define R_G3_FUNCID_MLME_START_CNF              (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_START))
#define R_G3_FUNCID_MCPS_DATA_IND               (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3MAC, R_G3_CMDID_MCPS_DATA))
#define R_G3_FUNCID_MLME_BEACON_NOTIFY_IND      (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_BEACON_NOTIFY))
#define R_G3_FUNCID_MLME_COMM_STATUS_IND        (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_COMM_STATUS))
#define R_G3_FUNCID_MLME_FRAMECOUNT_IND         (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_FRAMECOUNT))
#define R_G3_FUNCID_MLME_TMR_RECEIVE_IND        (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_TMR_RECEIVE))
#define R_G3_FUNCID_MLME_TMR_TRANSMIT_IND       (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3MAC, R_G3_CMDID_MLME_TMR_TRANSMIT))

#define R_G3_FUNCID_ADPD_DATA_REQ               (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPD_DATA))
#define R_G3_FUNCID_ADPM_RESET_REQ              (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_RESET))
#define R_G3_FUNCID_ADPM_DISCOVERY_REQ          (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_DISCOVERY))
#define R_G3_FUNCID_ADPM_NETWORK_START_REQ      (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_NETWORK_START))
#define R_G3_FUNCID_ADPM_NETWORK_JOIN_REQ       (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_NETWORK_JOIN))
#define R_G3_FUNCID_ADPM_NETWORK_LEAVE_REQ      (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_NETWORK_LEAVE))
#define R_G3_FUNCID_ADPM_GET_REQ                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_GET))
#define R_G3_FUNCID_ADPM_SET_REQ                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_SET))
#define R_G3_FUNCID_ADPM_ROUTE_DISCOVERY_REQ    (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_ROUTE_DISCOVERY))
#define R_G3_FUNCID_ADPM_PATH_DISCOVERY_REQ     (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_PATH_DISCOVERY))
#define R_G3_FUNCID_ADPM_LBP_REQ                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_LBP))
#define R_G3_FUNCID_ADPD_DATA_CNF               (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPD_DATA))
#define R_G3_FUNCID_ADPM_RESET_CNF              (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_RESET))
#define R_G3_FUNCID_ADPM_DISCOVERY_CNF          (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_DISCOVERY))
#define R_G3_FUNCID_ADPM_NETWORK_START_CNF      (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_NETWORK_START))
#define R_G3_FUNCID_ADPM_NETWORK_JOIN_CNF       (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_NETWORK_JOIN))
#define R_G3_FUNCID_ADPM_NETWORK_LEAVE_CNF      (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_NETWORK_LEAVE))
#define R_G3_FUNCID_ADPM_GET_CNF                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_GET))
#define R_G3_FUNCID_ADPM_SET_CNF                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_SET))
#define R_G3_FUNCID_ADPM_ROUTE_DISCOVERY_CNF    (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_ROUTE_DISCOVERY))
#define R_G3_FUNCID_ADPM_PATH_DISCOVERY_CNF     (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_PATH_DISCOVERY))
#define R_G3_FUNCID_ADPM_LBP_CNF                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_LBP))
#define R_G3_FUNCID_ADPD_DATA_IND               (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPD_DATA))
#define R_G3_FUNCID_ADPM_NETWORK_LEAVE_IND      (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_NETWORK_LEAVE))
#define R_G3_FUNCID_ADPM_PATH_DISCOVERY_IND     (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_PATH_DISCOVERY))
#define R_G3_FUNCID_ADPM_LBP_IND                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_LBP))
#define R_G3_FUNCID_ADPM_NETWORK_STATUS_IND     (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_NETWORK_STATUS))
#define R_G3_FUNCID_ADPM_BUFFER_IND             (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_BUFFER))
#define R_G3_FUNCID_ADPM_KEY_STATE_IND          (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_KEY_STATE))
#define R_G3_FUNCID_ADPM_ROUTE_ERROR_IND        (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_ROUTE_ERROR))
#define R_G3_FUNCID_ADPM_EAP_KEY_IND            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_EAP_KEY))
#define R_G3_FUNCID_ADPM_FRAME_COUNTER_IND      (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_FRAME_COUNTER))
#define R_G3_FUNCID_ADPM_ROUTE_UPDATE_IND       (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_ROUTE_UPDATE))
#define R_G3_FUNCID_ADPM_LOAD_SEQ_NUM_IND       (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_LOAD_SEQ_NUM))
#define R_G3_FUNCID_ADPM_RREP_IND               (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_RREP))
#define R_G3_FUNCID_ADPM_BEACON_NOTIFY_IND      (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3ADP, R_G3_CMDID_ADPM_BEACON_NOTIFY))

#define R_G3_FUNCID_EAPM_RESET_REQ              (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_RESET))
#define R_G3_FUNCID_EAPM_START_REQ              (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_START))
#define R_G3_FUNCID_EAPM_GET_REQ                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_GET))
#define R_G3_FUNCID_EAPM_SET_REQ                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_SET))
#define R_G3_FUNCID_EAPM_NETWORK_REQ            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_NETWORK))
#define R_G3_FUNCID_EAPM_SETCLIENTINFO_REQ      (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_SETCLIENTINFO))
#define R_G3_FUNCID_EAPM_RESET_CNF              (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_RESET))
#define R_G3_FUNCID_EAPM_START_CNF              (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_START))
#define R_G3_FUNCID_EAPM_GET_CNF                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_GET))
#define R_G3_FUNCID_EAPM_SET_CNF                (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_SET))
#define R_G3_FUNCID_EAPM_NETWORK_CNF            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_NETWORK))
#define R_G3_FUNCID_EAPM_SETCLIENTINFO_CNF      (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_SETCLIENTINFO))
#define R_G3_FUNCID_EAPM_NETWORK_JOIN_IND       (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_NETWORK_JOIN))
#define R_G3_FUNCID_EAPM_NETWORK_LEAVE_IND      (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_NETWORK_LEAVE))
#define R_G3_FUNCID_EAPM_NEWDEVICE_IND          (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_NEWDEVICE))
#define R_G3_FUNCID_EAPM_EAP_KEY_IND            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3EAP, R_G3_CMDID_EAPM_EAP_KEY))

#define R_G3_CMDID_RF_LML_DATA                  (0x05u)

#define R_G3_CMDID_RF_MCPS_DATA                 (0x00u)
#define R_G3_CMDID_RF_MLME_RESET                (0x01u)
#define R_G3_CMDID_RF_MLME_GET                  (0x02u)
#define R_G3_CMDID_RF_MLME_SET                  (0x03u)
#define R_G3_CMDID_RF_MLME_SCAN                 (0x04u)
#define R_G3_CMDID_RF_MLME_START                (0x05u)
#define R_G3_CMDID_RF_MLME_BEACON_NOTIFY        (0x06u)
#define R_G3_CMDID_RF_MLME_COMM_STATUS          (0x07u)
#define R_G3_CMDID_RF_MLME_FRAMECOUNT           (0x08u)
#define R_G3_CMDID_RF_MLME_WARNING              (0x0Au)
#define R_G3_CMDID_RF_MCPS_LML_DATA             (0x0Cu)

#define R_G3_CMDID_G3RFMAC_MAX                  (R_G3_CMDID_RF_MCPS_LML_DATA + 1u)

#define R_G3_FUNCID_RF_LML_DATA_IND             (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_RFLMAC, R_G3_CMDID_RF_LML_DATA))

#define R_G3_FUNCID_RF_MCPS_DATA_REQ            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MCPS_DATA))
#define R_G3_FUNCID_RF_MLME_RESET_REQ           (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_RESET))
#define R_G3_FUNCID_RF_MLME_GET_REQ             (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_GET))
#define R_G3_FUNCID_RF_MLME_SET_REQ             (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_SET))
#define R_G3_FUNCID_RF_MLME_SCAN_REQ            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_SCAN))
#define R_G3_FUNCID_RF_MLME_START_REQ           (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_REQ, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_START))
#define R_G3_FUNCID_RF_MCPS_DATA_CNF            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MCPS_DATA))
#define R_G3_FUNCID_RF_MLME_RESET_CNF           (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_RESET))
#define R_G3_FUNCID_RF_MLME_GET_CNF             (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_GET))
#define R_G3_FUNCID_RF_MLME_SET_CNF             (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_SET))
#define R_G3_FUNCID_RF_MLME_SCAN_CNF            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_SCAN))
#define R_G3_FUNCID_RF_MLME_START_CNF           (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_CNF, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_START))
#define R_G3_FUNCID_RF_MCPS_DATA_IND            (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MCPS_DATA))
#define R_G3_FUNCID_RF_MLME_BEACON_NOTIFY_IND   (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_BEACON_NOTIFY))
#define R_G3_FUNCID_RF_MLME_COMM_STATUS_IND     (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_COMM_STATUS))
#define R_G3_FUNCID_RF_MLME_FRAMECOUNT_IND      (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_FRAMECOUNT))
#define R_G3_FUNCID_RF_MLME_WARNING_IND         (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MLME_WARNING))
#define R_G3_FUNCID_RF_MCPS_LML_DATA_IND        (R_G3_MAKE_FUNCID (R_G3_CMDTYPE_IND, R_G3_UNITID_G3RFMAC, R_G3_CMDID_RF_MCPS_LML_DATA))
/******************************************************************************
Macro definitions
******************************************************************************/

/******************************************************************************
Typedef definitions
******************************************************************************/

/******************************************************************************
Exported global variables
******************************************************************************/

/******************************************************************************
Exported global functions (to be accessed by other files)
******************************************************************************/


#endif /* R_G3_CMD_H */

